"""Update user model

Revision ID: 977510895f2e
Revises: 
Create Date: 2025-08-19 14:27:02.574438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '977510895f2e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.alter_column('geom',
               existing_type=sa.NUMERIC(),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.create_index('idx_location_geom', ['geom'], unique=False, postgresql_using='gist')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_index('idx_location_geom', postgresql_using='gist')
        batch_op.alter_column('geom',
               existing_type=sa.Text(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    # ### end Alembic commands ###
